### ISSUE TITLE
甲骨文服务器使用问题

### ISSUE THREAD

**Issue by repairer7** [397179459/iMaoTai-reserve#2]
本地运行或github action一切正常
甲骨文服务器运行login.py接收不到验证码，直接运行main.py报错

**Comment by repairer7** [comment]
![IMG_9871](https://github.com/397179459/iMaoTai-reserve/assets/51566775/f9c3471b-be45-4965-a8d0-d7aa1f6e0c74)

**Comment by 397179459** [comment]
@repairer7 看起来像是编码问题，action也是在Ubuntu上跑的，没问题。
你把process#261行下面打印一下`params`和`headers`，看一下字段是乱码。
