### ISSUE TITLE
新年龙茅了

### ISSUE THREAD

**Issue by repairer7** [397179459/iMaoTai-reserve#24]
是否有更新？

**Comment by xcloudss** [comment]
改下商品ID就行了。
ITEM_MAP = {
            "10941": "53%vol 500ml贵州茅台酒（甲辰龙年）",
            "10942": "53%vol 375ml×2贵州茅台酒（癸卯兔年）",
            "10056": "53%vol 500ml茅台1935",
            "2478": "53%vol 500ml贵州茅台酒（珍品）"
}

ITEM_CODES = ['10941', '10942']   # 需要预约的商品(默认只预约2个赚钱的茅子)

**Comment by NoahAmethyst** [comment]
> 改下商品ID就行了。 ITEM_MAP = { "10941": "53%vol 500ml贵州茅台酒（甲辰龙年）", "10942": "53%vol 375ml×2贵州茅台酒（癸卯兔年）", "10056": "53%vol 500ml茅台1935", "2478": "53%vol 500ml贵州茅台酒（珍品）" }
> 
> ITEM_CODES = ['10941', '10942'] # 需要预约的商品(默认只预约2个赚钱的茅子)

有获取商品id的接口吗

**Comment by Lkdyyyy** [comment]
ITEM_MAP = {
    "10941": "53%vol 500ml贵州茅台酒（甲辰龙年）",
    "10942": "53%vol 375ml×2贵州茅台酒（甲辰龙年）",
    "10056": "53%vol 500ml茅台1935",
    "2478": "53%vol 500ml贵州茅台酒（珍品）"
}
 


# 需要预约的商品(默认只预约2个兔茅)
########################
ITEM_CODES = ['10941', '10942']

**Comment by 397179459** [comment]
> > 改下商品ID就行了。 ITEM_MAP = { "10941": "53%vol 500ml贵州茅台酒（甲辰龙年）", "10942": "53%vol 375ml×2贵州茅台酒（癸卯兔年）", "10056": "53%vol 500ml茅台1935", "2478": "53%vol 500ml贵州茅台酒（珍品）" }
> > ITEM_CODES = ['10941', '10942'] # 需要预约的商品(默认只预约2个赚钱的茅子)
> 
> 有获取商品id的接口吗

研究一下 `process.py` #149 那个request
