### ISSUE TITLE
小白提问，本地运行成功，Actions运行失败

### ISSUE THREAD

**Issue by niustark** [397179459/iMaoTai-reserve#37]
1.请问本地修改后的  myConfig/credentials 文件需要推送到云端才能运行Actions吗
![screenshot-1705389971414](https://github.com/397179459/iMaoTai-reserve/assets/28669447/e9ed6fad-f910-45f0-b076-e7bd78b1f29c)

> Run python main.py
  python main.py
  shell: /usr/bin/bash -e {0}
  env:
    TZ: Asia/Shanghai
    pythonLocation: /opt/hostedtoolcache/Python/3.10.13/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.13/x64/lib
    PUSHPLUS_KEY: 
    PRIVATE_AES_KEY: 
Traceback (most recent call last):
  File "/home/runner/work/iMaoTai-reserve/iMaoTai-reserve/main.py", line 41, in <module>

    mobile = privateCrypt.decrypt_aes_ecb(section, aes_key)
  File "/home/runner/work/iMaoTai-reserve/iMaoTai-reserve/privateCrypt.py", line 43, in decrypt_aes_ecb
    plain_str = unpad(cipher.decrypt(ciphertext), AES.block_size)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/Crypto/Util/Padding.py", line 9[2](https://github.com/niustark/iMaoTai-reserve/actions/runs/7535870152/job/20512487665#step:6:2), in unpad
    raise ValueError("Padding is incorrect.")
ValueError: Padding is incorrect.
**************************************
    欢迎使用i茅台自动预约工具
    作者GitHub：https://github.com/[3](https://github.com/niustark/iMaoTai-reserve/actions/runs/7535870152/job/20512487665#step:6:3) 9 7 1 7 9 [4](https://github.com/niustark/iMaoTai-reserve/actions/runs/7535870152/job/20512487665#step:6:4) [5](https://github.com/niustark/iMaoTai-reserve/actions/runs/7535870152/job/20512487665#step:6:5) 9
    vx：L 3 9 [7](https://github.com/niustark/iMaoTai-reserve/actions/runs/7535870152/job/20512487665#step:6:7) 1 7 [9](https://github.com/niustark/iMaoTai-reserve/actions/runs/7535870152/job/20512487665#step:6:9) 4 5 9 加好友注明来意
**************************************

**Comment by seitaone** [comment]
你这个跟我一样的错

**Comment by seitaone** [comment]
> 1.请问本地修改后的 myConfig/credentials 文件需要推送到云端才能运行Actions吗 ![screenshot-1705389971414](https://private-user-images.githubusercontent.com/28669447/296966028-e9ed6fad-f910-45f0-b076-e7bd78b1f29c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTY0MTQsIm5iZiI6MTcwNTQ1NjExNCwicGF0aCI6Ii8yODY2OTQ0Ny8yOTY5NjYwMjgtZTllZDZmYWQtZjkxMC00NWYwLWIwNzYtZTdiZDc4YjFmMjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAxNDgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNmQ2ZDRiYWIyMGVkNzFkZjkzM2QwNTVmYzBhZDdjOWRiMzNmY2U4ODBiYTVkNmJkZTdhNzJiMDc3Y2MxMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q_WM-fbVRafeXUghMYuVZpBRHlYQItDJw2PL-UDewcw)
> 
> > Run python main.py
> > python main.py
> > shell: /usr/bin/bash -e {0}
> > env:
> > TZ: Asia/Shanghai
> > pythonLocation: /opt/hostedtoolcache/Python/3.10.13/x64
> > LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.13/x64/lib
> > PUSHPLUS_KEY:
> > PRIVATE_AES_KEY:
> > Traceback (most recent call last):
> > File "/home/runner/work/iMaoTai-reserve/iMaoTai-reserve/main.py", line 41, in
> 
> ```
> mobile = privateCrypt.decrypt_aes_ecb(section, aes_key)
> ```
> 
> File "/home/runner/work/iMaoTai-reserve/iMaoTai-reserve/privateCrypt.py", line 43, in decrypt_aes_ecb plain_str = unpad(cipher.decrypt(ciphertext), AES.block_size) File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/Crypto/Util/Padding.py", line 9[2](https://github.com/niustark/iMaoTai-reserve/actions/runs/7535870152/job/20512487665#step:6:2), in unpad raise ValueError("Padding is incorrect.") ValueError: Padding is incorrect.
> 
> ```
> 欢迎使用i茅台自动预约工具
> 作者GitHub：https://github.com/[3](https://github.com/niustark/iMaoTai-reserve/actions/runs/7535870152/job/20512487665#step:6:3) 9 7 1 7 9 [4](https://github.com/niustark/iMaoTai-reserve/actions/runs/7535870152/job/20512487665#step:6:4) [5](https://github.com/niustark/iMaoTai-reserve/actions/runs/7535870152/job/20512487665#step:6:5) 9
> vx：L 3 9 [7](https://github.com/niustark/iMaoTai-reserve/actions/runs/7535870152/job/20512487665#step:6:7) 1 7 [9](https://github.com/niustark/iMaoTai-reserve/actions/runs/7535870152/job/20512487665#step:6:9) 4 5 9 加好友注明来意
> ```
我的成功了，就是没有配置那个环境变量

**Comment by niustark** [comment]
> 我的成功了，就是没有配置那个环境变量
PRIVATE_AES_KEY  是怎么设置的?我这老是Actions 运行出错
![screenshot-1705466334071](https://github.com/397179459/iMaoTai-reserve/assets/28669447/48f012ac-274c-46db-a95d-ac297bfccf32)

**Comment by niustark** [comment]
终于成功运行Actions了
