### ISSUE TITLE
小白请教下已经在本地跑起来了，如何实现不要服务器，每日自动运行抢茅台呢

### ISSUE THREAD

**Issue by seitaone** [397179459/iMaoTai-reserve#39]
5、配置 Github actions，每日自动预约，省去自己买服务器的成本。
先Fork本项目，再去自己的项目中配置PUSHPLUS_KEY和和PRIVATE_AES_KEY

就这步没有看懂，其他都懂了

**Comment by seitaone** [comment]
报这个错了，现在

**Comment by seitaone** [comment]
![报错](https://github.com/397179459/iMaoTai-reserve/assets/17918391/0a06b2a3-c93d-4d7b-aa25-d7f1ae2eef2f)
报这个错

**Comment by abubaff** [comment]
我和你问题一模一样 ，啊！！！

**Comment by abubaff** [comment]
> ![报错](https://private-user-images.githubusercontent.com/17918391/297005057-0a06b2a3-c93d-4d7b-aa25-d7f1ae2eef2f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MDc3OTQsIm5iZiI6MTcwNTQwNzQ5NCwicGF0aCI6Ii8xNzkxODM5MS8yOTcwMDUwNTctMGEwNmIyYTMtYzkzZC00ZDdiLWFhMjUtZDdmMWFlMmVlZjJmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEyMTgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkYTQyMzVjZjBiOWVhZDA2OGQ3MmVhMWE4OGM5NWE4OWI2M2UzZTU4ZWE0NmJmNDk3MjZkZmYxZDkzMmU5ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l0OnZ6aeJHAZM77RA295e6dSC7hJ2sqQvrYb7A29UTE) 报这个错

我知道问题了，你看下是不是你加密的和解密的密钥不一样

**Comment by abubaff** [comment]
可以在本地测试一下，用一个密钥生成个人信息；再换一个密钥就能复现这个问题

**Comment by seitaone** [comment]
> 可以在本地测试一下，用一个密钥生成个人信息；再换一个密钥就能复现这个问题

我就是在本地测试成功了，把myConfig配置下的credentials配置文件复制进去的

**Comment by seitaone** [comment]
> > ![报错](https://private-user-images.githubusercontent.com/17918391/297005057-0a06b2a3-c93d-4d7b-aa25-d7f1ae2eef2f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MDc3OTQsIm5iZiI6MTcwNTQwNzQ5NCwicGF0aCI6Ii8xNzkxODM5MS8yOTcwMDUwNTctMGEwNmIyYTMtYzkzZC00ZDdiLWFhMjUtZDdmMWFlMmVlZjJmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEyMTgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkYTQyMzVjZjBiOWVhZDA2OGQ3MmVhMWE4OGM5NWE4OWI2M2UzZTU4ZWE0NmJmNDk3MjZkZmYxZDkzMmU5ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l0OnZ6aeJHAZM77RA295e6dSC7hJ2sqQvrYb7A29UTE) 报这个错
> 
> 我知道问题了，你看下是不是你加密的和解密的密钥不一样

你最终成功没得呢

**Comment by seitaone** [comment]
> 试一下，用一个密钥生成个人信息；

感谢，成功了
