### ISSUE TITLE
login 获取不到验证码

### ISSUE THREAD

**Issue by wwkGit** [397179459/iMaoTai-reserve#4]

**Comment by wwkGit** [comment]
我用的是初代的代码，上上周还可以，但是现在报接口500了 ，而且重新login 获取不到验证码了

**Comment by wwkGit** [comment]
![image](https://github.com/397179459/iMaoTai-reserve/assets/45025686/79d6078c-839d-4f48-9b29-8f42bd5d7da0)

**Comment by 397179459** [comment]
![image](https://github.com/397179459/iMaoTai-reserve/assets/44400790/352b56ed-faaa-4f23-a6d3-283a87283044)
这个版本专门针对这个乱码修复了

**Comment by wwkGit** [comment]
嗯嗯 我试了新版 没问题了
