### ISSUE TITLE
关于触发时间的问题

### ISSUE THREAD

**Issue by yirenzhi** [397179459/iMaoTai-reserve#5]
请问下
- cron: '20 0,1 * * *'
为何设置成这样，i茅台的预约时间应该是早上9-10点，这样设置我的理解是8.20和9.20触发是吗
为何要如此设置呢

**Comment by 397179459** [comment]
因为会delay，而且是无固定时间的delay。关于Github actions的cron实际运行时间一直是世界未解之谜。
这个问题已经有很多讨论了。可以看一下[Github合作伙伴的讨论](https://github.com/orgs/community/discussions/27130)

**Comment by yirenzhi** [comment]
好的，感谢回答
