### ISSUE TITLE
执行main.py报错Padding is incorrect

### ISSUE THREAD

**Issue by sbzhaopeng** [397179459/iMaoTai-reserve#6]
Traceback (most recent call last):
  File "/arcadia/repo/397179459_iMaoTai-reserve/main.py", line 41, in <module>
    mobile = privateCrypt.decrypt_aes_ecb(section, aes_key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/arcadia/repo/397179459_iMaoTai-reserve/privateCrypt.py", line 43, in decrypt_aes_ecb
    plain_str = unpad(cipher.decrypt(ciphertext), AES.block_size)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/Crypto/Util/Padding.py", line 92, in unpad
    raise ValueError("Padding is incorrect.")
ValueError: Padding is incorrect.

**Comment by huangyue4727603** [comment]
删一下myconfig里面的文件

**Comment by 397179459** [comment]
你是直接执行的`main.py`吗？需要先执行`login.py`进行配置

**Comment by yellowfish621** [comment]
解决了吗 怎么操作的

**Comment by yyanyi213** [comment]
> 你是直接执行的`main.py`吗？需要先执行`login.py`进行配置

我是在actions里运行的时候出现的这个padding的问题，本地运行main.py是没有问题的，这个怎么解决啊？

**Comment by qq727127158** [comment]
笔者也被此问题困扰数小时，发现本地python版本为3.12.1。运行无问题，githubAction的版本为3.10。修改githubAction中python版本为3.12.1后Action运行正常。此问题可能是python3.10自身的bug。
