### ISSUE TITLE
Schedule cron是不是写的有问题啊

### ISSUE THREAD

**Issue by Vensent** [397179459/iMaoTai-reserve#62]
2024年4月15日这天好像没有触发哦。

作者的Action我看了下没有触发，我自己fork的项目也没有触发

**Comment by ClancyChang** [comment]
对的，4.15没有触发，好奇怪

**Comment by Vensent** [comment]
看了下Github上面说的这个Action的Schedule就是容易遇到延迟或者不触发的情况，我准备把代码放到其他地方，然后这里流水线报错是怎么回事呢？
![image](https://github.com/397179459/iMaoTai-reserve/assets/7401921/6612ea6f-d9c0-4181-a167-2c22028e59f0)
