### ISSUE TITLE
Main文件好像没执行成功呀，大佬帮忙看看

### ISSUE THREAD

**Issue by wuxing55** [397179459/iMaoTai-reserve#65]
然后执行Action报错，main.py : ERROR  配置文件未找到配置
![image](https://github.com/397179459/iMaoTai-reserve/assets/81150480/1b7fd56d-45da-47fd-a6fa-d082766a0585)
![image](https://github.com/397179459/iMaoTai-reserve/assets/81150480/000d77b0-89aa-4d73-b3c7-6a6722e71cdd)

**Comment by 397179459** [comment]
你是不没有运行login.py配置过
